#!/bin/sh

echo '[+] add3_boolean'
build/bench/add3_boolean 2> /dev/null | grep 'BM'
echo '[+] add3_lut3'
build/bench/add3_lut3 2> /dev/null | grep 'BM'
echo '[+] add3_lut3fa'
build/bench/add3_lut3fa 2> /dev/null | grep 'BM'
echo '[+] add4_boolean'
build/bench/add4_boolean 2> /dev/null | grep 'BM'
echo '[+] add4_lut3'
build/bench/add4_lut3 2> /dev/null | grep 'BM'
echo '[+] add4_lut3fa'
build/bench/add4_lut3fa 2> /dev/null | grep 'BM'
echo '[+] calculator_boolean'
build/bench/calculator_boolean 2> /dev/null | grep 'BM'
echo '[+] calculator_lut3'
build/bench/calculator_lut3 2> /dev/null | grep 'BM'
echo '[+] calculator_lut3fa'
build/bench/calculator_lut3fa 2> /dev/null | grep 'BM'
echo '[+] const4_boolean'
build/bench/const4_boolean 2> /dev/null | grep 'BM'
echo '[+] const4_lut3'
build/bench/const4_lut3 2> /dev/null | grep 'BM'
echo '[+] const4_lut3fa'
build/bench/const4_lut3fa 2> /dev/null | grep 'BM'
echo '[+] image_gaussian_boolean'
build/bench/image_gaussian_boolean 2> /dev/null | grep 'BM'
echo '[+] image_gaussian_lut3'
build/bench/image_gaussian_lut3 2> /dev/null | grep 'BM'
echo '[+] image_gaussian_lut3fa'
build/bench/image_gaussian_lut3fa 2> /dev/null | grep 'BM'
echo '[+] image_ricker_boolean'
build/bench/image_ricker_boolean 2> /dev/null | grep 'BM'
echo '[+] image_ricker_lut3'
build/bench/image_ricker_lut3 2> /dev/null | grep 'BM'
echo '[+] image_ricker_lut3fa'
build/bench/image_ricker_lut3fa 2> /dev/null | grep 'BM'
echo '[+] image_sharpen_boolean'
build/bench/image_sharpen_boolean 2> /dev/null | grep 'BM'
echo '[+] image_sharpen_lut3'
build/bench/image_sharpen_lut3 2> /dev/null | grep 'BM'
echo '[+] image_sharpen_lut3fa'
build/bench/image_sharpen_lut3fa 2> /dev/null | grep 'BM'
echo '[+] sqrt_boolean'
build/bench/sqrt_boolean 2> /dev/null | grep 'BM'
echo '[+] sqrt_lut3'
build/bench/sqrt_lut3 2> /dev/null | grep 'BM'
echo '[+] sqrt_lut3fa'
build/bench/sqrt_lut3fa 2> /dev/null | grep 'BM'
echo '[+] strrev_boolean'
build/bench/strrev_boolean 2> /dev/null | grep 'BM'
echo '[+] strrev_lut3'
build/bench/strrev_lut3 2> /dev/null | grep 'BM'
echo '[+] strrev_lut3fa'
build/bench/strrev_lut3fa 2> /dev/null | grep 'BM'
echo '[+] structs_1d_boolean'
build/bench/structs_1d_boolean 2> /dev/null | grep 'BM'
echo '[+] structs_1d_lut3'
build/bench/structs_1d_lut3 2> /dev/null | grep 'BM'
echo '[+] structs_1d_lut3fa'
build/bench/structs_1d_lut3fa 2> /dev/null | grep 'BM'
echo '[+] structs_3d_boolean'
build/bench/structs_3d_boolean 2> /dev/null | grep 'BM'
echo '[+] structs_3d_lut3'
build/bench/structs_3d_lut3 2> /dev/null | grep 'BM'
echo '[+] structs_3d_lut3fa'
build/bench/structs_3d_lut3fa 2> /dev/null | grep 'BM'
echo '[+] sum3d_boolean'
build/bench/sum3d_boolean 2> /dev/null | grep 'BM'
echo '[+] sum3d_lut3'
build/bench/sum3d_lut3 2> /dev/null | grep 'BM'
echo '[+] sum3d_lut3fa'
build/bench/sum3d_lut3fa 2> /dev/null | grep 'BM'
echo '[+] sum_boolean'
build/bench/sum_boolean 2> /dev/null | grep 'BM'
echo '[+] sum_lut3'
build/bench/sum_lut3 2> /dev/null | grep 'BM'
echo '[+] sum_lut3fa'
build/bench/sum_lut3fa 2> /dev/null | grep 'BM'
